[phases.setup]
nixPkgs = ["python311", "nodejs-20_x", "gcc"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt",
    "npm install",
    "npm run build"
]

[start]
cmd = "python -m uvicorn app.backend.main:app --host 0.0.0.0 --port $PORT" 