[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "nodejs_20", "gcc"]

[phases.install]
cmds = [
    "python3 --version",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt",
    "chmod +x railway-build.sh",
    "./railway-build.sh"
]

[start]
cmd = "python3 start_server.py" 