[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "chmod +x railway-build.sh",
    "./railway-build.sh"
]

[start]
cmd = "python start_server.py" 