[build]
builder = "nixpacks"
buildCommand = "poetry install"

[deploy]
startCommand = "poetry run uvicorn app.backend.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11"
PORT = "8000" 