[build]
builder = "nixpacks"
buildCommand = """
curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
apt-get install -y nodejs && \
poetry install --no-dev --no-interaction && \
cd app/frontend && \
npm install --no-audit --no-fund && \
npm run build && \
cd /app
"""

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
maxRetries = 5

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8000"
PYTHON_VERSION = "3.11.7"
NODE_VERSION = "20.x" 