[build]
builder = "nixpacks"
buildCommand = "poetry install --no-dev"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicy = "on-failure"
maxRetries = 10

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8000" 