[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn app.backend.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
maxRetries = 5

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
NIXPACKS_PYTHON_VERSION = "3.11" 